/*
  Auto-generated by Spline
*/

import useSpline from '@splinetool/r3f-spline'

const Rocket = ({...props}) => {
	const {nodes, materials} = useSpline('https://prod.spline.design/BEzwniZqQRRSCGXu/scene.splinecode')
	return (
		<>
			<group {...props} scale={0.2} dispose={null}>
				<group name="Rocket" position={[0, 100.45, 0]}>
					<group name="Pieds" position={[0, -83.95, 0]} rotation={[0, Math.PI / 4, 0]}>
						<group name="Pied" position={[22.57, 4.55, 0]} rotation={[0, 0, -0.1]} scale={[0.1, 0.39, 0.08]}>
							<mesh
								name="Object_7"
								geometry={nodes.Object_7.geometry}
								material={nodes.Object_7.material}
								castShadow
								receiveShadow
							/>
						</group>
						<group name="Pied1" position={[0.1, 4.24, -21.12]} rotation={[1.39, 1.53, -1.39]} scale={[0.1, 0.39, 0.08]}>
							<mesh
								name="Object_9"
								geometry={nodes.Object_9.geometry}
								material={nodes.Object_9.material}
								castShadow
								receiveShadow
							/>
						</group>
						<group name="Pied2" position={[-22.07, 4.6, 0]} rotation={[Math.PI, 0, 3.04]} scale={[0.1, 0.39, 0.08]}>
							<mesh
								name="Object_11"
								geometry={nodes.Object_11.geometry}
								material={nodes.Object_11.material}
								castShadow
								receiveShadow
							/>
						</group>
						<group
							name="Pied3"
							position={[0.1, 5.05, 21.71]}
							rotation={[-1.39, -1.53, -1.39]}
							scale={[0.1, 0.39, 0.08]}
						>
							<mesh
								name="Object_13"
								geometry={nodes.Object_13.geometry}
								material={nodes.Object_13.material}
								castShadow
								receiveShadow
							/>
						</group>
					</group>
					<group
						name="Hublot"
						position={[-2.13, -36.47, 14.08]}
						rotation={[-Math.PI / 2, Math.PI / 2, 0]}
						scale={[0.36, 0.59, 0.36]}
					/>
					<group name="Forme_base" position={[0.14, -49.71, 0]}>
						<group name="Cone_Haut" position={[0.37, 41.85, 0]} scale={[0.87, 0.33, 0.88]}>
							<mesh
								name="Object_5"
								geometry={nodes.Object_5.geometry}
								material={nodes.Object_5.material}
								castShadow
								receiveShadow
							/>
						</group>
						<group name="Corps_Bas" position={[0.21, -32.2, 0]} scale={[2.16, 1, 2.18]}>
							<mesh
								name="Porte"
								geometry={nodes.Porte.geometry}
								material={materials['Porte Material']}
								castShadow
								receiveShadow
								position={[-0.1, 0.03, 8.07]}
								scale={[0.46, 1, 0.46]}
							/>
							<mesh
								name="Bas"
								geometry={nodes.Bas.geometry}
								material={materials['Bas Material']}
								castShadow
								receiveShadow
								scale={[0.46, 1, 0.46]}
							>
								<mesh
									name="Trou porte 2"
									geometry={nodes['Trou porte 2'].geometry}
									material={materials['Trou porte 2 Material']}
									visible={false}
									castShadow
									receiveShadow
									position={[-0.21, -0.68, -16.18]}
									scale={[1.51, 1.12, 1.06]}
								/>
								<mesh
									name="Object_18"
									geometry={nodes.Object_18.geometry}
									material={nodes.Object_18.material}
									visible={false}
									castShadow
									receiveShadow
									scale={[2.16, 1, 2.18]}
								/>
							</mesh>
						</group>
						<group name="Corps_Haut" position={[0.37, 1.49, 0]} scale={[2.62, 1, 2.65]}>
							<mesh
								name="Haut"
								geometry={nodes.Haut.geometry}
								material={materials['Haut Material']}
								castShadow
								receiveShadow
								scale={[0.38, 1, 0.38]}
							/>
							<mesh
								name="Object_21"
								geometry={nodes.Object_21.geometry}
								material={nodes.Object_21.material}
								castShadow
								receiveShadow
							/>
						</group>
					</group>
				</group>
			</group>
		</>
	)
}

export default Rocket