/*
  Auto-generated by Spline
*/

import useSpline from '@splinetool/r3f-spline'

const Arcade = ({ ...props }) => {
  const { nodes } = useSpline('https://prod.spline.design/VcMDlYaYZkTXg0MT/scene.splinecode')
  return (
    <>
      <group {...props} position={[0, -0.5, 0]} dispose={null} scale={0.008} rotation={[0, (-90 * Math.PI) / 180, 0]}>
        <group name="Arcade">
          <mesh
            name="cadre_005"
            geometry={nodes.cadre_005.geometry}
            material={nodes.cadre_005.material}
            castShadow
            receiveShadow
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <mesh
              name="tendeur_001"
              geometry={nodes.tendeur_001.geometry}
              material={nodes.tendeur_001.material}
              castShadow
              receiveShadow
              position={[-1.58, 0.21, 0.94]}
              rotation={[-Math.PI / 2, 0, -Math.PI]}
            />
            <mesh
              name="vis_de_serrage_axe_arrière003"
              geometry={nodes.vis_de_serrage_axe_arrière003.geometry}
              material={nodes.vis_de_serrage_axe_arrière003.material}
              castShadow
              receiveShadow
              position={[-1.58, 0.16, 0.94]}
              scale={[0.98, 0.55, 0.98]}
            />
            <mesh
              name="fourche002"
              geometry={nodes.fourche002.geometry}
              material={nodes.fourche002.material}
              castShadow
              receiveShadow
              position={[1.05, 0, 2.09]}
              rotation={[0, -0.26, 0]}
              scale={0.64}
            >
              <mesh
                name="pneu_avant001"
                geometry={nodes.pneu_avant001.geometry}
                material={nodes.pneu_avant001.material}
                castShadow
                receiveShadow
                position={[0.11, 0, -1.87]}
                rotation={[0, 0.22, 0]}
                scale={1.56}
              >
                <mesh
                  name="Bouchon_bite_de_chambre002"
                  geometry={nodes.Bouchon_bite_de_chambre002.geometry}
                  material={nodes.Bouchon_bite_de_chambre002.material}
                  castShadow
                  receiveShadow
                  position={[-0.04, 0, -0.68]}
                />
                <mesh
                  name="Vis_de_disque_avant"
                  geometry={nodes.Vis_de_disque_avant.geometry}
                  material={nodes.Vis_de_disque_avant.material}
                  castShadow
                  receiveShadow
                  position={[0, 0.13, 0]}
                />
                <mesh
                  name="rayons_avant_final001"
                  geometry={nodes.rayons_avant_final001.geometry}
                  material={nodes.rayons_avant_final001.material}
                  castShadow
                  receiveShadow
                  position={[0, 0.04, 0]}
                  rotation={[0, 0.74, 0]}
                />
                <mesh
                  name="moyeux_avant_002"
                  geometry={nodes.moyeux_avant_002.geometry}
                  material={nodes.moyeux_avant_002.material}
                  castShadow
                  receiveShadow
                  position={[0, 0.04, 0]}
                  scale={0.98}
                >
                  <mesh
                    name="disque_de_frein_arrière002"
                    geometry={nodes.disque_de_frein_arrière002.geometry}
                    material={nodes.disque_de_frein_arrière002.material}
                    castShadow
                    receiveShadow
                    position={[0, 0.09, 0]}
                    scale={1.02}
                  />
                </mesh>
                <mesh
                  name="jante_avant_001"
                  geometry={nodes.jante_avant_001.geometry}
                  material={nodes.jante_avant_001.material}
                  castShadow
                  receiveShadow
                />
                <mesh
                  name="Vis_de_rayon_avant_"
                  geometry={nodes.Vis_de_rayon_avant_.geometry}
                  material={nodes.Vis_de_rayon_avant_.material}
                  castShadow
                  receiveShadow
                  rotation={[0, Math.PI / 4, 0]}
                />
                <mesh
                  name="Bite_de_chambre_jante_avant_"
                  geometry={nodes.Bite_de_chambre_jante_avant_.geometry}
                  material={nodes.Bite_de_chambre_jante_avant_.material}
                  castShadow
                  receiveShadow
                  position={[-0.04, 0, -0.67]}
                  rotation={[0, 0.06, 0]}
                />
              </mesh>
              <mesh
                name="vis_006"
                geometry={nodes.vis_006.geometry}
                material={nodes.vis_006.material}
                castShadow
                receiveShadow
                position={[-0.09, 0.28, -1.53]}
                rotation={[-Math.PI / 2, 0, -2.88]}
                scale={1.56}
              />
              <mesh
                name="vis_007"
                geometry={nodes.vis_007.geometry}
                material={nodes.vis_007.material}
                castShadow
                receiveShadow
                position={[-0.21, 0.25, -1.42]}
                rotation={[0, -1.57, -1.57]}
                scale={1.56}
              />
              <mesh
                name="vis_008"
                geometry={nodes.vis_008.geometry}
                material={nodes.vis_008.material}
                castShadow
                receiveShadow
                position={[-0.22, 0.25, -1.81]}
                rotation={[0, -1.54, -1.57]}
                scale={1.56}
              />
              <mesh
                name="potence007"
                geometry={nodes.potence007.geometry}
                material={nodes.potence007.material}
                castShadow
                receiveShadow
                position={[0.3, 0, 1.06]}
                rotation={[-Math.PI, -0.98, -Math.PI]}
                scale={[-1.11, 1.11, 1.11]}
              >
                <mesh
                  name="cintre001"
                  geometry={nodes.cintre001.geometry}
                  material={nodes.cintre001.material}
                  castShadow
                  receiveShadow
                  position={[0, 0, -0.06]}
                  rotation={[-Math.PI, -0.53, -Math.PI]}
                  scale={[-1.48, 1.48, 1.48]}
                >
                  <mesh
                    name="grip_droit_001"
                    geometry={nodes.grip_droit_001.geometry}
                    material={nodes.grip_droit_001.material}
                    castShadow
                    receiveShadow
                  />
                  <mesh
                    name="grip_gauche_001"
                    geometry={nodes.grip_gauche_001.geometry}
                    material={nodes.grip_gauche_001.material}
                    castShadow
                    receiveShadow
                    rotation={[0, 0, -Math.PI]}
                    scale={[-1, 1, 1]}
                  />
                  <mesh
                    name="manette002"
                    geometry={nodes.manette002.geometry}
                    material={nodes.manette002.material}
                    castShadow
                    receiveShadow
                    position={[0.07, -0.46, 0.16]}
                    rotation={[-0.1, -1.06, 1.57]}
                    scale={[-1.4, 1.4, 1.4]}
                  >
                    <mesh
                      name="Circle022"
                      geometry={nodes.Circle022.geometry}
                      material={nodes.Circle022.material}
                      castShadow
                      receiveShadow
                      position={[0.02, 0.02, 0.06]}
                      rotation={[-Math.PI / 2, 0, 0]}
                      scale={0.68}
                    />
                    <mesh
                      name="freein_1004"
                      geometry={nodes.freein_1004.geometry}
                      material={nodes.freein_1004.material}
                      castShadow
                      receiveShadow
                      position={[0.09, 0, -0.08]}
                      rotation={[-1.57, -0.02, -0.02]}
                      scale={[-0.37, 0.37, 0.37]}
                    >
                      <mesh
                        name="Plane003"
                        geometry={nodes.Plane003.geometry}
                        material={nodes.Plane003.material}
                        castShadow
                        receiveShadow
                        position={[0.2, -0.07, 0]}
                        rotation={[-0.01, 0.02, -0.85]}
                        scale={[-1.27, 1.27, 1.27]}
                      />
                      <mesh
                        name="Circle023"
                        geometry={nodes.Circle023.geometry}
                        material={nodes.Circle023.material}
                        castShadow
                        receiveShadow
                        position={[0.24, 0.06, 0]}
                        rotation={[-1.59, 0.41, 0.02]}
                        scale={[-0.04, 0.04, 0.04]}
                      />
                    </mesh>
                    <mesh
                      name="Circle019"
                      geometry={nodes.Circle019.geometry}
                      material={nodes.Circle019.material}
                      castShadow
                      receiveShadow
                      position={[0.02, -0.01, 0.01]}
                      rotation={[0, 0.74, -Math.PI]}
                      scale={[-0.01, 0.01, 0.01]}
                    />
                    <mesh
                      name="Circle021"
                      geometry={nodes.Circle021.geometry}
                      material={nodes.Circle021.material}
                      castShadow
                      receiveShadow
                      position={[0.02, 0.01, 0.01]}
                      rotation={[0, 0.74, 0]}
                      scale={0.01}
                    />
                  </mesh>
                  <mesh
                    name="manette003"
                    geometry={nodes.manette003.geometry}
                    material={nodes.manette003.material}
                    castShadow
                    receiveShadow
                    position={[0.07, 0.46, 0.16]}
                    rotation={[0.14, -1.06, 1.63]}
                    scale={1.4}
                  >
                    <mesh
                      name="freein_1005"
                      geometry={nodes.freein_1005.geometry}
                      material={nodes.freein_1005.material}
                      castShadow
                      receiveShadow
                      position={[0.09, 0, -0.08]}
                      rotation={[-Math.PI / 2, 0, 0]}
                      scale={[-0.37, 0.37, 0.37]}
                    >
                      <mesh
                        name="Circle017"
                        geometry={nodes.Circle017.geometry}
                        material={nodes.Circle017.material}
                        castShadow
                        receiveShadow
                        position={[0.24, 0.06, 0]}
                        rotation={[-1.59, 0.41, 0.02]}
                        scale={[-0.04, 0.04, 0.04]}
                      />
                      <mesh
                        name="Plane004"
                        geometry={nodes.Plane004.geometry}
                        material={nodes.Plane004.material}
                        castShadow
                        receiveShadow
                        position={[0.2, -0.07, 0]}
                        rotation={[-0.01, 0.02, -0.85]}
                        scale={[-1.27, 1.27, 1.27]}
                      />
                    </mesh>
                    <mesh
                      name="Circle025"
                      geometry={nodes.Circle025.geometry}
                      material={nodes.Circle025.material}
                      castShadow
                      receiveShadow
                      position={[0.02, 0.01, 0.01]}
                      rotation={[0, 0.74, 0]}
                      scale={0.01}
                    />
                    <mesh
                      name="Circle026"
                      geometry={nodes.Circle026.geometry}
                      material={nodes.Circle026.material}
                      castShadow
                      receiveShadow
                      position={[0.02, 0.02, 0.06]}
                      rotation={[-Math.PI / 2, 0, 0]}
                      scale={0.68}
                    />
                    <mesh
                      name="Circle024"
                      geometry={nodes.Circle024.geometry}
                      material={nodes.Circle024.material}
                      castShadow
                      receiveShadow
                      position={[0.02, -0.01, 0.01]}
                      rotation={[0, 0.74, -Math.PI]}
                      scale={[-0.01, 0.01, 0.01]}
                    />
                    <mesh
                      name="freein_1003"
                      geometry={nodes.freein_1003.geometry}
                      material={nodes.freein_1003.material}
                      castShadow
                      receiveShadow
                      position={[0.09, 0, -0.08]}
                      rotation={[Math.PI / 2, 0, Math.PI]}
                      scale={0.37}
                    />
                  </mesh>
                </mesh>
                <mesh
                  name="Vis_de_potence_2"
                  geometry={nodes.Vis_de_potence_2.geometry}
                  material={nodes.Vis_de_potence_2.material}
                  castShadow
                  receiveShadow
                  position={[-0.04, 0.03, 0.4]}
                  rotation={[-Math.PI / 2, 0, 0.71]}
                  scale={[-0.78, 0.78, 0.78]}
                />
                <mesh
                  name="capot_de_fourche_001"
                  geometry={nodes.capot_de_fourche_001.geometry}
                  material={nodes.capot_de_fourche_001.material}
                  castShadow
                  receiveShadow
                  position={[-0.12, 0, 0.24]}
                  rotation={[0, 0.98, 0]}
                  scale={0.96}
                />
                <mesh
                  name="Vis_potence"
                  geometry={nodes.Vis_potence.geometry}
                  material={nodes.Vis_potence.material}
                  castShadow
                  receiveShadow
                  position={[0, 0, -0.07]}
                />
              </mesh>
              <mesh
                name="Vert007"
                geometry={nodes.Vert007.geometry}
                material={nodes.Vert007.material}
                castShadow
                receiveShadow
                position={[-0.12, 0.27, -1.63]}
                rotation={[0, -1.19, 0]}
                scale={1.56}
              />
              <mesh
                name="etrier_de_frein_003"
                geometry={nodes.etrier_de_frein_003.geometry}
                material={nodes.etrier_de_frein_003.material}
                castShadow
                receiveShadow
                position={[-0.23, 0.24, -1.62]}
                rotation={[-Math.PI / 2, 0, 2.13]}
                scale={0.06}
              >
                <mesh
                  name="déco_etrier_de_frein_1001"
                  geometry={nodes.déco_etrier_de_frein_1001.geometry}
                  material={nodes.déco_etrier_de_frein_1001.material}
                  castShadow
                  receiveShadow
                />
                <mesh
                  name="déco_etrier_de_frein_2001"
                  geometry={nodes.déco_etrier_de_frein_2001.geometry}
                  material={nodes.déco_etrier_de_frein_2001.material}
                  castShadow
                  receiveShadow
                />
                <mesh
                  name="vis_de_plaquettes013"
                  geometry={nodes.vis_de_plaquettes013.geometry}
                  material={nodes.vis_de_plaquettes013.material}
                  castShadow
                  receiveShadow
                  position={[-40.5, -33.35, 8.78]}
                  rotation={[-Math.PI / 2, 0, Math.PI]}
                  scale={27.26}
                />
                <mesh
                  name="pistons003"
                  geometry={nodes.pistons003.geometry}
                  material={nodes.pistons003.material}
                  castShadow
                  receiveShadow
                  position={[-40.5, -33.35, 8.88]}
                  rotation={[-Math.PI / 2, 0, Math.PI]}
                  scale={27.26}
                />
                <mesh
                  name="vis_de_plaquettes012"
                  geometry={nodes.vis_de_plaquettes012.geometry}
                  material={nodes.vis_de_plaquettes012.material}
                  castShadow
                  receiveShadow
                  position={[-40.5, -33.35, 8.78]}
                  rotation={[-Math.PI / 2, 0, Math.PI]}
                  scale={27.26}
                />
                <mesh
                  name="plaquette_de_freins_002"
                  geometry={nodes.plaquette_de_freins_002.geometry}
                  material={nodes.plaquette_de_freins_002.material}
                  castShadow
                  receiveShadow
                  position={[-40.5, -33.35, 8.88]}
                  rotation={[-Math.PI / 2, 0, Math.PI]}
                  scale={27.26}
                />
                <mesh
                  name="vis_de_plaquettes015"
                  geometry={nodes.vis_de_plaquettes015.geometry}
                  material={nodes.vis_de_plaquettes015.material}
                  castShadow
                  receiveShadow
                  position={[-40.5, -33.35, 9.08]}
                  rotation={[-Math.PI / 2, 0, Math.PI]}
                  scale={27.26}
                />
                <mesh
                  name="bout_de_gaine_003"
                  geometry={nodes.bout_de_gaine_003.geometry}
                  material={nodes.bout_de_gaine_003.material}
                  castShadow
                  receiveShadow
                  position={[-2.77, 1.01, -1.69]}
                  rotation={[-0.19, -1.34, -2.3]}
                  scale={27.26}
                />
                <mesh
                  name="vis_de_plaquettes014"
                  geometry={nodes.vis_de_plaquettes014.geometry}
                  material={nodes.vis_de_plaquettes014.material}
                  castShadow
                  receiveShadow
                  position={[-40.5, -33.35, 8.88]}
                  rotation={[-Math.PI / 2, 0, Math.PI]}
                  scale={27.26}
                />
              </mesh>
              <mesh
                name="vis_de_serrage_axe_avant002"
                geometry={nodes.vis_de_serrage_axe_avant002.geometry}
                material={nodes.vis_de_serrage_axe_avant002.material}
                castShadow
                receiveShadow
                position={[0.11, 0.2, -1.87]}
                rotation={[0, 0.26, 0]}
                scale={[1.52, 0.86, 1.52]}
              />
              <mesh
                name="vis_de_serrage_axe_avant003"
                geometry={nodes.vis_de_serrage_axe_avant003.geometry}
                material={nodes.vis_de_serrage_axe_avant003.material}
                castShadow
                receiveShadow
                position={[0.11, -0.19, -1.87]}
                rotation={[0, 0.26, -Math.PI]}
                scale={[-1.52, 0.86, 1.52]}
              />
              <mesh
                name="Entretoise_fourche"
                geometry={nodes.Entretoise_fourche.geometry}
                material={nodes.Entretoise_fourche.material}
                castShadow
                receiveShadow
                position={[0, 0, 0.74]}
              />
              <mesh
                name="entretoise_fourche_001"
                geometry={nodes.entretoise_fourche_001.geometry}
                material={nodes.entretoise_fourche_001.material}
                castShadow
                receiveShadow
                rotation={[Math.PI, 0, -Math.PI]}
                scale={[-1.56, 1.56, 1.56]}
              />
            </mesh>
            <mesh
              name="selle002"
              geometry={nodes.selle002.geometry}
              material={nodes.selle002.material}
              castShadow
              receiveShadow
              position={[-0.82, 0, 1.82]}
              rotation={[0, -0.43, 0]}
            />
            <mesh
              name="pneu_arriere001"
              geometry={nodes.pneu_arriere001.geometry}
              material={nodes.pneu_arriere001.material}
              castShadow
              receiveShadow
              position={[-1.58, 0, 0.94]}
              rotation={[0, -1.2, 0]}
            >
              <mesh
                name="pignon001"
                geometry={nodes.pignon001.geometry}
                material={nodes.pignon001.material}
                castShadow
                receiveShadow
                position={[0, -0.12, 0]}
              />
              <mesh
                name="rayons_arrière_002"
                geometry={nodes.rayons_arrière_002.geometry}
                material={nodes.rayons_arrière_002.material}
                castShadow
                receiveShadow
                position={[0, 0.06, 0]}
              />
              <mesh
                name="Bite_de_chambre"
                geometry={nodes.Bite_de_chambre.geometry}
                material={nodes.Bite_de_chambre.material}
                castShadow
                receiveShadow
                position={[0, 0, -0.67]}
              />
              <mesh
                name="jante_arriere_001"
                geometry={nodes.jante_arriere_001.geometry}
                material={nodes.jante_arriere_001.material}
                castShadow
                receiveShadow
              />
              <mesh
                name="Vis_de_rayon"
                geometry={nodes.Vis_de_rayon.geometry}
                material={nodes.Vis_de_rayon.material}
                castShadow
                receiveShadow
                position={[0, 0.06, 0]}
              />
              <mesh
                name="moyeux_arriere_001"
                geometry={nodes.moyeux_arriere_001.geometry}
                material={nodes.moyeux_arriere_001.material}
                castShadow
                receiveShadow
                position={[0, 0.06, 0]}
              >
                <mesh
                  name="disque_de_frein_arrière001"
                  geometry={nodes.disque_de_frein_arrière001.geometry}
                  material={nodes.disque_de_frein_arrière001.material}
                  castShadow
                  receiveShadow
                  position={[0, 0.11, 0]}
                  rotation={[0, Math.PI / 3, 0]}
                >
                  <mesh
                    name="Vis_de_disque_avant001"
                    geometry={nodes.Vis_de_disque_avant001.geometry}
                    material={nodes.Vis_de_disque_avant001.material}
                    castShadow
                    receiveShadow
                  />
                </mesh>
              </mesh>
              <mesh
                name="Bouchon_bite_de_chambre001"
                geometry={nodes.Bouchon_bite_de_chambre001.geometry}
                material={nodes.Bouchon_bite_de_chambre001.material}
                castShadow
                receiveShadow
                position={[0, 0, -0.67]}
              />
            </mesh>
            <mesh
              name="Circle015"
              geometry={nodes.Circle015.geometry}
              material={nodes.Circle015.material}
              castShadow
              receiveShadow
              position={[-1.58, -0.17, 0.94]}
              rotation={[-Math.PI / 2, 0, -Math.PI]}
            />
            <mesh
              name="vis_005"
              geometry={nodes.vis_005.geometry}
              material={nodes.vis_005.material}
              castShadow
              receiveShadow
              position={[-1.35, 0.18, 1.23]}
              rotation={[0, -0.27, -Math.PI]}
              scale={1.3}
            />
            <mesh
              name="Vert002"
              geometry={nodes.Vert002.geometry}
              material={nodes.Vert002.material}
              castShadow
              receiveShadow
              position={[-1.48, 0.19, 1.12]}
            />
            <mesh
              name="Circle014"
              geometry={nodes.Circle014.geometry}
              material={nodes.Circle014.material}
              castShadow
              receiveShadow
              position={[-1.58, 0.21, 0.94]}
              rotation={[-Math.PI / 2, 0, -Math.PI]}
            />
            <mesh
              name="vis_009"
              geometry={nodes.vis_009.geometry}
              material={nodes.vis_009.material}
              castShadow
              receiveShadow
              position={[-1.42, 0.2, 1.12]}
              rotation={[-Math.PI / 2, 0, -Math.PI]}
              scale={1.3}
            />
            <mesh
              name="entretoise_fourche_2001"
              geometry={nodes.entretoise_fourche_2001.geometry}
              material={nodes.entretoise_fourche_2001.material}
              castShadow
              receiveShadow
              position={[0.93, 0, 2.51]}
              rotation={[Math.PI, 0.26, -Math.PI]}
              scale={[-1, 1, 1]}
            />
            <mesh
              name="Joint_de_selle"
              geometry={nodes.Joint_de_selle.geometry}
              material={nodes.Joint_de_selle.material}
              castShadow
              receiveShadow
              position={[-0.7, -0.05, 1.64]}
              rotation={[Math.PI / 2, 0, 0]}
              scale={1.12}
            />
            <mesh
              name="pedalier001"
              geometry={nodes.pedalier001.geometry}
              material={nodes.pedalier001.material}
              castShadow
              receiveShadow
              position={[-0.47, 0, 1.02]}
              rotation={[-Math.PI / 2, 0, 2.14]}
              scale={0.55}
            >
              <mesh
                name="serre_pedalier_2001"
                geometry={nodes.serre_pedalier_2001.geometry}
                material={nodes.serre_pedalier_2001.material}
                castShadow
                receiveShadow
                position={[0, 0, -0.21]}
                rotation={[Math.PI / 2, 0.2, 0]}
                scale={1.83}
              />
              <mesh
                name="serre_pedalier_001"
                geometry={nodes.serre_pedalier_001.geometry}
                material={nodes.serre_pedalier_001.material}
                castShadow
                receiveShadow
                position={[0, 0, 0.21]}
                rotation={[Math.PI / 2, 0.2, -Math.PI]}
                scale={[-1.83, 1.83, 1.83]}
              />
              <mesh
                name="vis_serrage_axe_pedalier_003"
                geometry={nodes.vis_serrage_axe_pedalier_003.geometry}
                material={nodes.vis_serrage_axe_pedalier_003.material}
                castShadow
                receiveShadow
                position={[0, 0, 0.32]}
                rotation={[Math.PI, 0, -Math.PI]}
                scale={[-1, 1, 1]}
              />
              <mesh
                name="vis_de_pedale_2001"
                geometry={nodes.vis_de_pedale_2001.geometry}
                material={nodes.vis_de_pedale_2001.material}
                castShadow
                receiveShadow
                position={[0, 0.76, 0.37]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={[0.21, 0.21, 0.04]}
              />
              <mesh
                name="pedale_2001"
                geometry={nodes.pedale_2001.geometry}
                material={nodes.pedale_2001.material}
                castShadow
                receiveShadow
                position={[0, 0.76, 0.43]}
                rotation={[-Math.PI / 2, -1, -Math.PI]}
                scale={[-0.02, 0.04, 0.04]}
              />
              <mesh
                name="vis_serrage_axe_pedalier_002"
                geometry={nodes.vis_serrage_axe_pedalier_002.geometry}
                material={nodes.vis_serrage_axe_pedalier_002.material}
                castShadow
                receiveShadow
                position={[0, 0, -0.32]}
              />
              <mesh
                name="vis_de_pedale_001"
                geometry={nodes.vis_de_pedale_001.geometry}
                material={nodes.vis_de_pedale_001.material}
                castShadow
                receiveShadow
                position={[0, -0.76, -0.37]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={[0.21, 0.21, 0.04]}
              />
              <mesh
                name="pedale_002"
                geometry={nodes.pedale_002.geometry}
                material={nodes.pedale_002.material}
                castShadow
                receiveShadow
                position={[0, -0.76, -0.43]}
                rotation={[Math.PI / 2, 1, Math.PI]}
                scale={[-0.02, 0.04, 0.04]}
              />
            </mesh>
            <mesh
              name="selle001"
              geometry={nodes.selle001.geometry}
              material={nodes.selle001.material}
              castShadow
              receiveShadow
              position={[-0.82, 0, 1.82]}
              rotation={[0, -0.43, 0]}
            />
            <mesh
              name="tendeur_2001"
              geometry={nodes.tendeur_2001.geometry}
              material={nodes.tendeur_2001.material}
              castShadow
              receiveShadow
              position={[-1.58, -0.21, 0.94]}
              rotation={[Math.PI / 2, 0, 0]}
              scale={[-1, 1, 1]}
            />
            <mesh
              name="etrier_de_frein_002"
              geometry={nodes.etrier_de_frein_002.geometry}
              material={nodes.etrier_de_frein_002.material}
              castShadow
              receiveShadow
              position={[-1.48, 0.17, 1.21]}
              rotation={[-Math.PI / 2, 0, -2.84]}
              scale={0.04}
            >
              <mesh
                name="pistons002"
                geometry={nodes.pistons002.geometry}
                material={nodes.pistons002.material}
                castShadow
                receiveShadow
                position={[1.4, -0.68, -0.78]}
              />
              <mesh
                name="vis_de_plaquettes008"
                geometry={nodes.vis_de_plaquettes008.geometry}
                material={nodes.vis_de_plaquettes008.material}
                castShadow
                receiveShadow
                position={[1.62, 0.65, 0.38]}
                scale={28.42}
              />
              <mesh
                name="vis_de_plaquettes011"
                geometry={nodes.vis_de_plaquettes011.geometry}
                material={nodes.vis_de_plaquettes011.material}
                castShadow
                receiveShadow
                position={[81.17, -30.88, -9.12]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={27.26}
              />
              <mesh
                name="vis_de_plaquettes010"
                geometry={nodes.vis_de_plaquettes010.geometry}
                material={nodes.vis_de_plaquettes010.material}
                castShadow
                receiveShadow
                position={[81.07, -30.83, 8.41]}
                rotation={[-Math.PI / 2, 0, Math.PI]}
                scale={[-27.26, 27.26, 27.26]}
              />
              <mesh
                name="Déco_etrier_de_freins_arrières_2001"
                geometry={nodes.Déco_etrier_de_freins_arrières_2001.geometry}
                material={nodes.Déco_etrier_de_freins_arrières_2001.material}
                castShadow
                receiveShadow
                position={[0.08, -0.14, 0.22]}
              />
              <mesh
                name="plaquette_de_freinqs_001"
                geometry={nodes.plaquette_de_freinqs_001.geometry}
                material={nodes.plaquette_de_freinqs_001.material}
                castShadow
                receiveShadow
                position={[-0.85, 0.65, -0.47]}
                rotation={[0, 0, 0.16]}
                scale={0.63}
              />
              <mesh
                name="bout_de_gaine_002"
                geometry={nodes.bout_de_gaine_002.geometry}
                material={nodes.bout_de_gaine_002.material}
                castShadow
                receiveShadow
                position={[-2.38, 0.84, -1.32]}
                rotation={[0.17, 0.38, 0.61]}
              />
              <mesh
                name="Déco_etrier_de_freins_arrières_1001"
                geometry={nodes.Déco_etrier_de_freins_arrières_1001.geometry}
                material={nodes.Déco_etrier_de_freins_arrières_1001.material}
                castShadow
                receiveShadow
                position={[0.08, -0.14, 0.22]}
              />
              <mesh
                name="vis_de_plaquettes009"
                geometry={nodes.vis_de_plaquettes009.geometry}
                material={nodes.vis_de_plaquettes009.material}
                castShadow
                receiveShadow
                position={[-0.85, 0.65, 0.38]}
                scale={28.42}
              />
            </mesh>
            <mesh
              name="Collier_colson_"
              geometry={nodes.Collier_colson_.geometry}
              material={nodes.Collier_colson_.material}
              castShadow
              receiveShadow
              position={[-0.11, 0.06, 1.84]}
              rotation={[2.46, 0.6, -2.54]}
              scale={[-1, 1, 1]}
            />
            <mesh
              name="Vis_de_selle"
              geometry={nodes.Vis_de_selle.geometry}
              material={nodes.Vis_de_selle.material}
              castShadow
              receiveShadow
              position={[-0.7, -0.05, 1.64]}
              rotation={[Math.PI / 2, 0, 0]}
              scale={1.12}
            />
            <mesh
              name="vis_de_serrage_axe_arrière002"
              geometry={nodes.vis_de_serrage_axe_arrière002.geometry}
              material={nodes.vis_de_serrage_axe_arrière002.material}
              castShadow
              receiveShadow
              position={[-1.58, -0.16, 0.94]}
              rotation={[0, 0, Math.PI]}
              scale={[-0.98, 0.55, 0.98]}
            />
          </mesh>
          <mesh
            name="cable_avant001"
            geometry={nodes.cable_avant001.geometry}
            material={nodes.cable_avant001.material}
            castShadow
            receiveShadow
            position={[125.14, 291.6, -40.93]}
            rotation={[-Math.PI / 2, 0, -Math.PI]}
            scale={[-100, 100, 100]}
          />
          <mesh
            name="cable_arriere001"
            geometry={nodes.cable_arriere001.geometry}
            material={nodes.cable_arriere001.material}
            castShadow
            receiveShadow
            position={[125.09, 291.6, 40.9]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
        </group>
      </group>
    </>
  )
}

export default Arcade