/*
  Auto-generated by Spline
*/

import useSpline from '@splinetool/r3f-spline'

const SignSkateparkSocial = ({...props}) => {
	const {nodes, materials} = useSpline('https://prod.spline.design/1UUCWuuewP53Rk4S/scene.splinecode')
	return (
		<>
			<group {...props} scale={0.008} dispose={null}>
				<group name="Skatepark_Grid" position={[-1, 455.83, 4.4]}>
					<group name="Panneau Social Media 2" position={[-12.55, 49.81, 25.71]} rotation={[0, -0.75, Math.PI]}>
						<group name="Social Medias txt" position={[-41.31, -10.04, 4.25]} rotation={[0, 0, -Math.PI]}>
							<group name="Text" position={[-29, -8.94, 0.77]}>
								<mesh
									name="S"
									geometry={nodes.S.geometry}
									material={materials['My Text Material']}
									castShadow
									receiveShadow
									position={[-125.83, -19.31, -5.73]}
								/>
								<mesh
									name="k"
									geometry={nodes.k.geometry}
									material={materials['My Text Material']}
									castShadow
									receiveShadow
									position={[-92.92, -19.31, -5.73]}
								/>
								<mesh
									name="a"
									geometry={nodes.a.geometry}
									material={materials['My Text Material']}
									castShadow
									receiveShadow
									position={[-65.87, -19.31, -5.73]}
								/>
								<mesh
									name="t"
									geometry={nodes.t.geometry}
									material={materials['My Text Material']}
									castShadow
									receiveShadow
									position={[-36.83, -19.31, -5.73]}
								/>
								<mesh
									name="e"
									geometry={nodes.e.geometry}
									material={materials['My Text Material']}
									castShadow
									receiveShadow
									position={[-18.59, -19.31, -5.73]}
								/>
								<mesh
									name="p"
									geometry={nodes.p.geometry}
									material={materials['My Text Material']}
									castShadow
									receiveShadow
									position={[9.3, -19.31, -5.73]}
								/>
								<mesh
									name="a1"
									geometry={nodes.a1.geometry}
									material={materials['My Text Material']}
									castShadow
									receiveShadow
									position={[39.28, -19.31, -5.73]}
								/>
								<mesh
									name="r"
									geometry={nodes.r.geometry}
									material={materials['My Text Material']}
									castShadow
									receiveShadow
									position={[68.31, -19.31, -5.73]}
								/>
								<mesh
									name="k1"
									geometry={nodes.k1.geometry}
									material={materials['My Text Material']}
									castShadow
									receiveShadow
									position={[86.4, -19.31, -5.73]}
								/>
							</group>
						</group>
						<group name="Panneau" position={[0, 0, -4.25]}>
							<mesh
								name="Sign1"
								geometry={nodes.Sign1.geometry}
								material={materials['Sign1 Material']}
								castShadow
								receiveShadow
								position={[-12.43, 0.5, -7.5]}
								scale={[3.49, 1, 1]}
							/>
							<mesh
								name="Triangle"
								geometry={nodes.Triangle.geometry}
								material={materials['Triangle Material']}
								castShadow
								receiveShadow
								position={[173.72, -0.5, -7.5]}
								rotation={[0, 0, -Math.PI / 2]}
							/>
						</group>
					</group>
					<group name="Panneau Social Media" position={[41.74, -78.33, 32.35]}>
						<group name="Social Medias txt1" position={[-41.31, 6, 4.25]}>
							<mesh
								name="S1"
								geometry={nodes.S1.geometry}
								material={materials['My Text Material']}
								castShadow
								receiveShadow
								position={[-149.33, -25.5, -6]}
							/>
							<mesh
								name="o"
								geometry={nodes.o.geometry}
								material={materials['My Text Material']}
								castShadow
								receiveShadow
								position={[-119.88, -25.5, -6]}
							/>
							<mesh
								name="c"
								geometry={nodes.c.geometry}
								material={materials['My Text Material']}
								castShadow
								receiveShadow
								position={[-93.06, -25.5, -6]}
							/>
							<mesh
								name="i"
								geometry={nodes.i.geometry}
								material={materials['My Text Material']}
								castShadow
								receiveShadow
								position={[-68, -25.5, -6]}
							/>
							<mesh
								name="i1"
								geometry={nodes.i1.geometry}
								material={materials['My Text Material']}
								castShadow
								receiveShadow
								position={[-68, -25.5, -6]}
							/>
							<mesh
								name="a2"
								geometry={nodes.a2.geometry}
								material={materials['My Text Material']}
								castShadow
								receiveShadow
								position={[-56.1, -25.5, -6]}
							/>
							<mesh
								name="l"
								geometry={nodes.l.geometry}
								material={materials['My Text Material']}
								castShadow
								receiveShadow
								position={[-30.12, -25.5, -6]}
							/>
							<mesh
								name="M"
								geometry={nodes.M.geometry}
								material={materials['My Text Material']}
								castShadow
								receiveShadow
								position={[-6.49, -25.5, -6]}
							/>
							<mesh
								name="e1"
								geometry={nodes.e1.geometry}
								material={materials['My Text Material']}
								castShadow
								receiveShadow
								position={[34.99, -25.5, -6]}
							/>
							<mesh
								name="d"
								geometry={nodes.d.geometry}
								material={materials['My Text Material']}
								castShadow
								receiveShadow
								position={[59.94, -25.5, -6]}
							/>
							<mesh
								name="i2"
								geometry={nodes.i2.geometry}
								material={materials['My Text Material']}
								castShadow
								receiveShadow
								position={[86.77, -25.5, -6]}
							/>
							<mesh
								name="i3"
								geometry={nodes.i3.geometry}
								material={materials['My Text Material']}
								castShadow
								receiveShadow
								position={[86.77, -25.5, -6]}
							/>
							<mesh
								name="a3"
								geometry={nodes.a3.geometry}
								material={materials['My Text Material']}
								castShadow
								receiveShadow
								position={[98.67, -25.5, -6]}
							/>
							<mesh
								name="s"
								geometry={nodes.s.geometry}
								material={materials['My Text Material']}
								castShadow
								receiveShadow
								position={[124.64, -25.5, -6]}
							/>
						</group>
						<group name="Panneau1" position={[0, 0, -4.25]}>
							<mesh
								name="Sign11"
								geometry={nodes.Sign11.geometry}
								material={materials['Sign11 Material']}
								castShadow
								receiveShadow
								position={[-42.74, 0.5, -7.5]}
								scale={[3.49, 1, 1]}
							/>
							<mesh
								name="Triangle1"
								geometry={nodes.Triangle1.geometry}
								material={materials['Triangle1 Material']}
								castShadow
								receiveShadow
								position={[173.72, -0.5, -7.5]}
								rotation={[0, 0, -Math.PI / 2]}
							/>
						</group>
					</group>
					<mesh
						name="Base_Cylinder"
						geometry={nodes.Base_Cylinder.geometry}
						material={materials['Base_Cylinder Material']}
						castShadow
						receiveShadow
						position={[0.47, -318.77, 0]}
						scale={[0.4, 4.2, 0.4]}
					/>
				</group>
			</group>
		</>
	)
}

export default SignSkateparkSocial;