/*
  Auto-generated by Spline
*/

import useSpline from '@splinetool/r3f-spline'

const SignSkateparkSocial = ({...props}) => {
  const {nodes, materials} = useSpline('https://prod.spline.design/1UUCWuuewP53Rk4S/scene.splinecode')
  return (
    <>
      <color attach="background" args={['#4b4d52']}/>
      <group {...props} scale={0.008} dispose={null}>
        <group name="Skatepark_Grid" position={[-1, 455.83, 4.4]}>
          <group name="Panneau Social Media 2" position={[-12.55, 49.81, 25.71]} rotation={[0, -0.75, Math.PI]}>
            <group name="Social Medias txt" position={[-41.31, -10.04, 4.25]} rotation={[0, 0, -Math.PI]}>
              <group name="Text" position={[-29, -8.94, 0.77]}>
                <mesh
                  name="S"
                  geometry={nodes.S.geometry}
                  castShadow
                  receiveShadow
                  position={[-125.83, -19.31, -5.73]}
                />
                <mesh
                  name="k"
                  geometry={nodes.k.geometry}
                  castShadow
                  receiveShadow
                  position={[-92.92, -19.31, -5.73]}
                />
                <mesh
                  name="a"
                  geometry={nodes.a.geometry}
                  castShadow
                  receiveShadow
                  position={[-65.87, -19.31, -5.73]}
                />
                <mesh
                  name="t"
                  geometry={nodes.t.geometry}
                  castShadow
                  receiveShadow
                  position={[-36.83, -19.31, -5.73]}
                />
                <mesh
                  name="e"
                  geometry={nodes.e.geometry}
                  castShadow
                  receiveShadow
                  position={[-18.59, -19.31, -5.73]}
                />
                <mesh
                  name="p"
                  geometry={nodes.p.geometry}
                  castShadow
                  receiveShadow
                  position={[9.3, -19.31, -5.73]}
                />
                <mesh
                  name="a1"
                  geometry={nodes.a1.geometry}
                  castShadow
                  receiveShadow
                  position={[39.28, -19.31, -5.73]}
                />
                <mesh
                  name="r"
                  geometry={nodes.r.geometry}
                  castShadow
                  receiveShadow
                  position={[68.31, -19.31, -5.73]}
                />
                <mesh
                  name="k1"
                  geometry={nodes.k1.geometry}
                  castShadow
                  receiveShadow
                  position={[86.4, -19.31, -5.73]}
                />
              </group>
            </group>
            <group name="Panneau" position={[0, 0, -4.25]}>
              <mesh
                name="Sign1"
                geometry={nodes.Sign1.geometry}
                castShadow
                receiveShadow
                position={[-12.43, 0.5, -7.5]}
                scale={[3.49, 1, 1]}
              >
                <meshStandardMaterial
                  attach="material"
                  color="#AD7645"
                />
              </mesh>
              <mesh
                name="Triangle"
                geometry={nodes.Triangle.geometry}
                castShadow
                receiveShadow
                position={[173.72, -0.5, -7.5]}
                rotation={[0, 0, -Math.PI / 2]}
              >
                <meshStandardMaterial
                  attach="material"
                  color="#AD7645"
                />
              </mesh>
            </group>
          </group>
          <group name="Panneau Social Media" position={[41.74, -78.33, 32.35]}>
            <group name="Social Medias txt1" position={[-41.31, 6, 4.25]}>
              <mesh
                name="S1"
                geometry={nodes.S1.geometry}
                castShadow
                receiveShadow
                position={[-149.33, -25.5, -6]}
              />
              <mesh
                name="o"
                geometry={nodes.o.geometry}
                castShadow
                receiveShadow
                position={[-119.88, -25.5, -6]}
              />
              <mesh
                name="c"
                geometry={nodes.c.geometry}
                castShadow
                receiveShadow
                position={[-93.06, -25.5, -6]}
              />
              <mesh
                name="i"
                geometry={nodes.i.geometry}
                castShadow
                receiveShadow
                position={[-68, -25.5, -6]}
              />
              <mesh
                name="i1"
                geometry={nodes.i1.geometry}
                castShadow
                receiveShadow
                position={[-68, -25.5, -6]}
              />
              <mesh
                name="a2"
                geometry={nodes.a2.geometry}
                castShadow
                receiveShadow
                position={[-56.1, -25.5, -6]}
              />
              <mesh
                name="l"
                geometry={nodes.l.geometry}
                castShadow
                receiveShadow
                position={[-30.12, -25.5, -6]}
              />
              <mesh
                name="M"
                geometry={nodes.M.geometry}
                castShadow
                receiveShadow
                position={[-6.49, -25.5, -6]}
              />
              <mesh
                name="e1"
                geometry={nodes.e1.geometry}
                castShadow
                receiveShadow
                position={[34.99, -25.5, -6]}
              />
              <mesh
                name="d"
                geometry={nodes.d.geometry}
                castShadow
                receiveShadow
                position={[59.94, -25.5, -6]}
              />
              <mesh
                name="i2"
                geometry={nodes.i2.geometry}
                castShadow
                receiveShadow
                position={[86.77, -25.5, -6]}
              />
              <mesh
                name="i3"
                geometry={nodes.i3.geometry}
                castShadow
                receiveShadow
                position={[86.77, -25.5, -6]}
              />
              <mesh
                name="a3"
                geometry={nodes.a3.geometry}
                castShadow
                receiveShadow
                position={[98.67, -25.5, -6]}
              />
              <mesh
                name="s"
                geometry={nodes.s.geometry}
                castShadow
                receiveShadow
                position={[124.64, -25.5, -6]}
              />
            </group>
            <group name="Panneau1" position={[0, 0, -4.25]}>
              <mesh
                name="Sign11"
                geometry={nodes.Sign11.geometry}
                castShadow
                receiveShadow
                position={[-42.74, 0.5, -7.5]}
                scale={[3.49, 1, 1]}
              >
                <meshStandardMaterial
                  attach="material"
                  color="#AD7645"
                />
              </mesh>
              <mesh
                name="Triangle1"
                geometry={nodes.Triangle1.geometry}
                castShadow
                receiveShadow
                position={[173.72, -0.5, -7.5]}
                rotation={[0, 0, -Math.PI / 2]}
              >
                <meshStandardMaterial
                  attach="material"
                  color="#AD7645"
                />
              </mesh>
            </group>
          </group>
          <mesh
            name="Base_Cylinder"
            geometry={nodes.Base_Cylinder.geometry}
            castShadow
            receiveShadow
            position={[0.47, -318.77, 0]}
            scale={[0.4, 4.2, 0.4]}
          >
            <meshStandardMaterial
              attach="material"
              color="#3d1c03"
            />
          </mesh>
        </group>
      </group>
    </>
  )
}

export default SignSkateparkSocial;