/*
  Auto-generated by Spline
*/

import useSpline from '@splinetool/r3f-spline'
import {useTexture} from "@react-three/drei"

const Github = ({...props}) => {
	const colors = useTexture({
		map: 'octocat.png'
	})
	const {nodes, materials} = useSpline('https://prod.spline.design/zeG8cAAxEqM53SwF/scene.splinecode')
	return (
		<>
			<group {...props} dispose={null}>
				<group name="GitHub" scale={0.01}>
					<mesh
						name="Octocat"
						geometry={nodes.Octocat.geometry}
						castShadow
						receiveShadow
						position={[0, 1.38, -0.72]}
					>
						<meshPhongMaterial
							{...colors}
							transparent
						/>
					</mesh>
					<group name="GitHub1" position={[13.39, 16.38, 0]} scale={5}>
						<mesh
							name="Main_Rectangle"
							geometry={nodes.Main_Rectangle.geometry}
							material={materials['Main_Rectangle Material']}
							castShadow
							receiveShadow
							position={[-2.68, -3.28, -5.46]}
							scale={[1, 1, 0.21]}
						/>
					</group>
				</group>
			</group>
		</>
	)
}

export default Github;