/*
  Auto-generated by Spline
*/

import useSpline from '@splinetool/r3f-spline'

const Instagram = ({...props}) => {
	const {nodes, materials} = useSpline('https://prod.spline.design/od2tglNboqEnA8P8/scene.splinecode')
	return (
		<>
			<group {...props} dispose={null}>
				<group name="Instagram" position={[0.15, 0, 0]} scale={0.05}>
					<group name="Upper_Photo" position={[12.88, 13.28, 0]}>
						<mesh
							name="Upper_photo_inner"
							geometry={nodes.Upper_photo_inner.geometry}
							material={materials['Upper_photo_inner Material']}
							position={[-12.24, -11.71, 3.06]}
							scale={[0.04, 0.04, 2]}
						/>
						<mesh
							name="Upper_photo_inner1"
							geometry={nodes.Upper_photo_inner1.geometry}
							material={materials['Upper_photo_inner1 Material']}
							position={[0, 0, 0.04]}
							scale={[0.02, 0.02, 1]}
						/>
						<mesh
							name="Upper_photo_in"
							geometry={nodes.Upper_photo_in.geometry}
							material={materials['Upper_photo_in Material']}
							position={[0, 0, -0.01]}
							scale={[0.06, 0.06, 1]}
						/>
						<mesh
							name="Upper_photo_out"
							geometry={nodes.Upper_photo_out.geometry}
							material={materials['Upper_photo_out Material']}
							position={[0, 0, -0.04]}
							scale={[0.1, 0.1, 1]}
						/>
					</group>
					<group name="Upper_colors" position={[-14.93, 13.87, -4.4]} scale={0.2}>
						<mesh
							name="Blue"
							geometry={nodes.Blue.geometry}
							material={materials['Blue Material']}
							position={[17.23, -85.1, 0]}
							scale={[0.25, 5.04, 4.27]}
						>
							<mesh
								name="Upper part cube 2"
								geometry={nodes['Upper part cube 2'].geometry}
								material={materials['Upper part cube 2 Material']}
								visible={false}
								position={[0, -8.18, 0]}
								scale={[1.06, 0.73, 0.27]}
							/>
							<mesh
								name="Upper part cube"
								geometry={nodes['Upper part cube'].geometry}
								material={materials['Upper part cube Material']}
								visible={false}
								scale={[1, 1, 0.21]}
							/>
						</mesh>
						<mesh
							name="Green"
							geometry={nodes.Green.geometry}
							material={materials['Green Material']}
							position={[5.76, -85.1, 0]}
							scale={[0.25, 5.04, 4.27]}
						>
							<mesh
								name="Upper part cube 21"
								geometry={nodes['Upper part cube 21'].geometry}
								material={materials['Upper part cube 21 Material']}
								visible={false}
								position={[0, -8.18, 0]}
								scale={[1.06, 0.73, 0.27]}
							/>
							<mesh
								name="Upper part cube1"
								geometry={nodes['Upper part cube1'].geometry}
								material={materials['Upper part cube1 Material']}
								visible={false}
								scale={[1, 1, 0.21]}
							/>
						</mesh>
						<mesh
							name="Yellow"
							geometry={nodes.Yellow.geometry}
							material={materials['Yellow Material']}
							position={[-5.64, -85.1, 0]}
							scale={[0.25, 5.04, 4.27]}
						>
							<mesh
								name="Upper part cube 22"
								geometry={nodes['Upper part cube 22'].geometry}
								material={materials['Upper part cube 22 Material']}
								visible={false}
								position={[0, -8.18, 0]}
								scale={[1.06, 0.73, 0.27]}
							/>
							<mesh
								name="Upper part cube2"
								geometry={nodes['Upper part cube2'].geometry}
								material={materials['Upper part cube2 Material']}
								visible={false}
								scale={[1, 1, 0.21]}
							/>
						</mesh>
						<mesh
							name="Red"
							geometry={nodes.Red.geometry}
							material={materials['Red Material']}
							position={[-17.23, -85.1, 0]}
							scale={[0.25, 5.04, 4.27]}
						>
							<mesh
								name="Upper part cube 23"
								geometry={nodes['Upper part cube 23'].geometry}
								material={materials['Upper part cube 23 Material']}
								visible={false}
								position={[0, -8.18, 0]}
								scale={[1.06, 0.73, 0.27]}
							/>
							<mesh
								name="Upper part cube3"
								geometry={nodes['Upper part cube3'].geometry}
								material={materials['Upper part cube3 Material']}
								visible={false}
								scale={[1, 1, 0.21]}
							/>
						</mesh>
					</group>
					<mesh
						name="Upper_Brown_Rectangle"
						geometry={nodes.Upper_Brown_Rectangle.geometry}
						material={materials['Upper_Brown_Rectangle Material']}
						position={[-2.68, -3.02, -5.46]}
						scale={[1.01, 1, 1.02]}
					>
						<mesh
							name="Upper part cube 24"
							geometry={nodes['Upper part cube 24'].geometry}
							material={materials['Upper part cube 24 Material']}
							visible={false}
							position={[0, -8.18, 0]}
							scale={[1.06, 0.73, 0.27]}
						/>
						<mesh
							name="Upper part cube4"
							geometry={nodes['Upper part cube4'].geometry}
							material={materials['Upper part cube4 Material']}
							visible={false}
							scale={[1, 1, 0.21]}
						/>
					</mesh>
					<group name="Main_Photo" position={[-3.68, -2.28, -1.53]} scale={0.2}>
						<mesh
							name="In_Photo"
							geometry={nodes.In_Photo.geometry}
							material={materials['In_Photo Material']}
							position={[0, 0, 0.32]}
							rotation={[Math.PI / 2, 0, 0]}
							scale={1.5}
						/>
						<mesh
							name="Outer_Photo"
							geometry={nodes.Outer_Photo.geometry}
							material={materials['Outer_Photo Material']}
							rotation={[Math.PI / 2, 0, 0]}
							scale={1.5}
						/>
						<mesh
							name="Main_Photo1"
							geometry={nodes.Main_Photo1.geometry}
							material={materials['Main_Photo1 Material']}
							rotation={[Math.PI / 2, 0, 0]}
							scale={1.5}
						/>
					</group>
					<mesh
						name="Main_Rectangle"
						geometry={nodes.Main_Rectangle.geometry}
						material={materials['Main_Rectangle Material']}
						castShadow
						receiveShadow
						position={[-2.68, -3.28, -5.46]}
						scale={[1, 1, 0.21]}
					/>
				</group>
			</group>
		</>
	)
}

export default Instagram;