/*
  Auto-generated by Spline
*/

import useSpline from '@splinetool/r3f-spline'

const LinkedIn = ({ ...props }) => {
  const { nodes, materials } = useSpline('https://prod.spline.design/mooCpt7BNXv14-J3/scene.splinecode')
  return (
    <>
      <group {...props} dispose={null}>
        <group name="LinkedIn" scale={0.01}>
          <group name="in Text" position={[8.43, 2.85, -8.16]}>
            <group name="in Text1" position={[-1.16, 13, 1.27]} scale={1.34}>
              <mesh
                name="i"
                geometry={nodes.i.geometry}
                material={materials['My Text Material']}
                castShadow
                receiveShadow
                position={[-60.64, -60.63, 0]}
              />
              <mesh
                name="i1"
                geometry={nodes.i1.geometry}
                material={materials['My Text Material']}
                castShadow
                receiveShadow
                position={[-60.64, -60.63, 0]}
              />
              <mesh
                name="n"
                geometry={nodes.n.geometry}
                material={materials['My Text Material']}
                castShadow
                receiveShadow
                position={[-21.68, -60.63, 0]}
              />
            </group>
          </group>
          <group name="Linked In" position={[13.39, 16.38, 0]} scale={5}>
            <mesh
              name="Main_Rectangle"
              geometry={nodes.Main_Rectangle.geometry}
              material={materials['Main_Rectangle Material']}
              castShadow
              receiveShadow
              position={[-2.68, -3.28, -5.46]}
              scale={[1, 1, 0.21]}
            />
          </group>
        </group>
      </group>
    </>
  )
}

export default LinkedIn;