/*
  Auto-generated by Spline
*/

import useSpline from '@splinetool/r3f-spline'

const JumpGrid = ({color, ...props}) => {
	const {nodes, materials} = useSpline('https://prod.spline.design/A1U8mlI2LTYXLClw/scene.splinecode')
	return (
		<>
			<group {...props} scale={0.009} dispose={null}>
				<group name="Skatepark_Grid" position={[-1, 350, 4.4]}>
					<group name="Bars" position={[0, 105.83, 0]}>
						<mesh
							name="Base rectangle 3"
							geometry={nodes['Base rectangle 3'].geometry}
							castShadow
							receiveShadow
							position={[325, 0, 0]}
							rotation={[-Math.PI / 2, Math.PI / 2, 0]}
							scale={[7, 0.52, 1]}
						>
							<meshStandardMaterial color={color}/>
						</mesh>
						<mesh
							name="Base rectangle 2"
							geometry={nodes['Base rectangle 2'].geometry}
							material={materials['Base rectangle 2 Material']}
							castShadow
							receiveShadow
							position={[-350, 0, 0]}
							rotation={[-Math.PI / 2, Math.PI / 2, 0]}
							scale={[7, 0.52, 1]}
						>
							<meshStandardMaterial color={color}/>
						</mesh>
						<mesh
							name="Base rectangle"
							geometry={nodes['Base rectangle'].geometry}
							material={materials['Base rectangle Material']}
							castShadow
							receiveShadow
							position={[0, -350, 0]}
							rotation={[-Math.PI / 2, 0, 0]}
							scale={[7, 0.52, 1]}
						>
							<meshStandardMaterial color={color}/>
						</mesh>
					</group>
					<mesh
						name="Base_Cylinder"
						geometry={nodes.Base_Cylinder.geometry}
						material={materials['Base_Cylinder Material']}
						castShadow
						receiveShadow
						position={[0.47, -350, 0]}
						scale={[0.4, 1, 0.4]}
					>
						<meshStandardMaterial color={color}/>
					</mesh>
				</group>
			</group>
		</>
	)
}

export default JumpGrid;