/*
  Auto-generated by Spline
*/

import useSpline from '@splinetool/r3f-spline'

const Pad = ({position, ...props}) => {
	const {nodes, materials} = useSpline('https://prod.spline.design/MZ12w9zCNGzodc13/scene.splinecode')
	return (
		<>
			<group {...props} position={position} scale={0.0085} dispose={null}>
				<mesh
					name="Pad"
					geometry={nodes.Pad.geometry}
					castShadow
					receiveShadow
					position={[0, -5, 0]}
					scale={[1, 3.42, 1]}
				>
					<meshStandardMaterial
						color={`#ffffff`}
					/>
					<mesh
						name="Pad hole"
						geometry={nodes['Pad hole'].geometry}
						material={materials['Pad hole Material']}
						visible={false}
						castShadow
						receiveShadow
						position={[0, -2.5, 0]}
						rotation={[-Math.PI / 2, 0, 0]}
						scale={[1.41, 1.08, 1]}
					/>
					<mesh
						name="Pad1"
						geometry={nodes.Pad1.geometry}
						material={materials['Pad1 Material']}
						visible={false}
						castShadow
						receiveShadow
						position={[0, -2.5, 0]}
						rotation={[-Math.PI / 2, 0, 0]}
						scale={[1.5, 1.15, 1]}
					/>
				</mesh>
			</group>
		</>
	)
}

export default Pad;
