import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Scene from '../components/Scene/Scene'

const Home = () => {
    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <h1>cc</h1>
            <Scene/>
        </div>
    )
}

export default Home